# config_directory/config.toml
[config]

[config.wallpaper]
# Whether to set the wallpaper or not
set = true

# The base command to run for applying the wallpaper. Keywords like {{ image }}
# or anything that works inside of hooks works here. You could also set a
# static color if you use the color keywords and the wallpaper setter supports
# it.
command = "awww img {{ image }}"

[templates.waybar]
input_path = '~/.config/matugen/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.hyprland]
input_path = '~/.config/matugen/hypr.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.kitty]
input_path = '~/.config/matugen/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.tmux]
input_path = '~/.config/matugen/tmux-colors.conf'
output_path = '~/.tmux/colors.conf'
post_hook = 'tmux source-file ~/.tmux/colors.conf'

[templates.neovim]
input_path = '~/.config/matugen/nvim-colors.lua'
output_path = '~/.config/nvim/lua/plugins/colors.lua'
# I can't get this hook to work -- we're just gonna have to 
# manually reload nvim if the theme changes
# post_hook = 'pkill -SIGUSR1 nvim'

[templates.spicetify]
input_path = '~/.config/matugen/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Matugen/color.ini'
post_hook = 'spicetify apply'

[templates.vencord]
input_path = '~/.config/matugen/midnight-discord.css'
output_path = '~/.config/Vencord/themes/midnight-discord.css'
