#!/bin/bash

echo -e "Move to repo head: $(git rev-parse --show-toplevel)\n"
cd "$(git rev-parse --show-toplevel)" || exit

git submodule foreach 'git push'
git add .
git commit -m "Update submodules"
git push
