#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)
gitmodules_path="$(git rev-parse --show-toplevel)/.gitmodules"

echo -e "Fast forward repo on branch $current_branch\n"

if [ -f gitmodules_path ]; then
    git submodule foreach "git stash"
    git submodule foreach "git pull --ff-only"
fi

git stash

git pull --ff-only 

git stash apply

if [ -f gitmodules_path ]; then
    git submodule foreach "git stash apply"
fi
