#!/bin/sh

current_branch=$(git rev-parse --abbrev-ref HEAD)

echo -e "Fast forward repo on branch $current_branch\n"

git submodule foreach "git stash"
git stash

git pull --ff-only origin "$current_branch"
git submodule update --init --recursive

git submodule foreach "git stash apply"
git stash apply
