#!/bin/sh

# hyprctl keyword monitor "desc:Acer Technologies ED270U P2 34250AF3B3W01, 2560x1440, auto, 1"
hyprctl keyword monitor "HDMI-A-1, preferred, 2560x1440, auto, 1"

hyprctl keyword workspace "1, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "2, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "3, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "4, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "5, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "6, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "7, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "8, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "9, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl keyword workspace "0, monitor:desc:Acer Technologies ED270U P2 34250AF3B3W01"

hyprctl dispatch moveworkspacetomonitor 1 "desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl dispatch moveworkspacetomonitor 2 "desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl dispatch moveworkspacetomonitor 3 "desc:Acer Technologies ED270U P2 34250AF3B3W01"

hyprctl dispatch moveworkspacetomonitor 6 "desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl dispatch moveworkspacetomonitor 7 "desc:Acer Technologies ED270U P2 34250AF3B3W01"
hyprctl dispatch moveworkspacetomonitor 8 "desc:Acer Technologies ED270U P2 34250AF3B3W01"

hyprctl keyword monitor "eDP-1,disable"
