#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <monitor_name>"
    exit 1
fi

NAME=$1

echo "single monitor clamshell: ${NAME[0]}"

# hyprctl eval "hl.monitor({output = \"$NAME\", mode = \"preferred\", position = \"auto\", scale = 1,})"
# hyprctl eval 'hl.monitor({output = "eDP-1", disabled = true})'
