#!/bin/sh

hyprctl keyword monitor "HDMI-A-1, preffered, 0x0, 1"
hyprctl keyword monitor "eDP-1, preferred, 0x1440, 1"

hyprctl dispatch moveworkspacetomonitor 1 "HDMI-A-1"
hyprctl dispatch moveworkspacetomonitor 2 "HDMI-A-1"
hyprctl dispatch moveworkspacetomonitor 3 "HDMI-A-1"
hyprctl dispatch moveworkspacetomonitor 4 "HDMI-A-1"
hyprctl dispatch moveworkspacetomonitor 5 "HDMI-A-1"
hyprctl dispatch moveworkspacetomonitor 6 "eDP-1"
hyprctl dispatch moveworkspacetomonitor 7 "eDP-1"
hyprctl dispatch moveworkspacetomonitor 8 "eDP-1"
hyprctl dispatch moveworkspacetomonitor 9 "eDP-1"
hyprctl dispatch moveworkspacetomonitor 10 "eDP-1"
