#!/bin/sh

hyprctl eval 'hl.monitor({output   = "eDP-1", mode     = "1920x1080@60", position = "0x1200", scale    = 1})'

hyprctl eval 'hl.monitor({output   = "DP-3", mode     = "1920x1200@59.95", position = "0x0", scale    = 1})'

hyprctl eval 'hl.monitor({ output   = "DP-4", mode     = "1920x1200@59.95", position = "1920x0", scale    = 1, transform = 1})'

hyprctl eval 'hl.dsp.workspace.move({ workspace="1", monitor = "DP-3"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="2", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="3", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="6", monitor = "DP-4"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="7", monitor = "DP-4"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="8", monitor = "DP-4"})'
