#!/bin/sh

hyprctl eval "hl.monitor({output = \"eDP-1\", disabled = false, mode = \"1920x1080@60\", position = \"auto\", scale = 1,})"

hyprctl eval 'hl.dsp.workspace.move({ workspace="1", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="2", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="3", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="6", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="7", monitor = "eDP-1"})'
hyprctl eval 'hl.dsp.workspace.move({ workspace="8", monitor = "eDP-1"})'
